subjects = [
    "3D Computer Graphics and Animation",
    "A10 Preparation (Financial Mathematics)",
    "A20 Preparation (Probability and Statistics)",
    "Academic Writing",
    "Accounting for Decision Making",
    "Accounting Information System",
    "Accounting Professional Ethics",
    "Accounting Theory",
    "Accounting/ Management Information System (AIS/ MIS)",
    "Accuracy Development",
    "Actuarial Accounting",
    "Adaptive Design",
    "Administrative Procedural Law",
    "Advance Financial Management",
    "Advanced Accounting 1",
    "Advanced Accounting 2",
    "Advanced Computer Graphics",
    "Advanced Cost Accounting",
    "Advanced Database System",
    "Advanced Game Programming",
    "Advanced Manufacturing and Sustainable Industry",
    "Advanced Mathematics of Finance",
    "Advertising and Integrated Marketing Communication",
    "Agrarian Law",
    "Agribusiness Innovation Management",
    "Agribusiness Management",
    "Agribusiness Marketing",
    "Agribusiness Risk",
    "Agricultural Economic",
    "Agricultural Production Technology",
    "Agrifood Tourism Management",
    "Air Pollution Control and Technology",
    "Alternative Dispute Resolution",
    "Ambassador's Experience",
    "Applied Illustration",
    "Applied Mathematics 1",
    "Applied Mathematics 2",
    "Architectural Behavior and Environment",
    "Architectural Computation",
    "Architectural Drawing",
    "Architectural Heritage",
    "Architectural Photography",
    "Architectural Research Method",
    "Architecture Basic Design Studio 1",
    "Architecture Basic Design Studio 1 (Studio)",
    "Architecture Design Studio 1",
    "Architecture Design Studio 1 (Studio)",
    "Architecture Design Studio 2",
    "Architecture Design Studio 2 (Studio)",
    "Architecture Design Studio 3",
    "Architecture Design Studio 3 (Studio)",
    "Area and Regional Studies",
    "Artificial Intelligence",
    "ASEAN Law",
    "Audio Visual Production Methods",
    "Auditing 1",
    "Auditing 2",
    "Authoritarianism and Democracy",
    "Automatic Navigation System",
    "Banking and Finance Law",
    "Basic Animation",
    "Basic Camera",
    "Basic Computer Graphics",
    "Basic Design Principles",
    "Basic Drawing",
    "Basic Visual Communication Design",
    "Big Data Project",
    "Big Data Technology",
    "Board Game Design",
    "Brand Management",
    "Building & Interior Material",
    "Building Construction 1",
    "Building Construction 2",
    "Building Structure and Utility: Basic",
    "Building Utilities",
    "Business and Academic Writing (Project)",
    "Business Communication",
    "Business Economics",
    "Business Ethic and Leaderships",
    "Business Ethics",
    "Business Finance",
    "Business in World Politics",
    "Business Law and Ethics",
    "Business Mathematics",
    "Business Process Analysis",
    "Business Research Methodology",
    "Business Statistics",
    "Calculus",
    "Calculus 1",
    "Calculus 2",
    "Calculus 3",
    "CapCut Project: Video Editing for TikTok Content",
    "Capital Market Law",
    "Capstone Design",
    "Capstone Project",
    "Carbon Markets and International Law",
    "Career and Leadership: Introduction to Environmental Engineering",
    "Career in Education",
    "Categorical Data Analysis",
    "Chemistry",
    "Chemistry 1",
    "Chemistry 2",
    "Child Development",
    "Citizenship",
    "Civil Society Organization in International Relations (Project-based)",
    "Civil-Military Relations",
    "Climate Change Adaptation and Mitigation",
    "Color and Light",
    "Commercial and Company Law",
    "Comparative Politics",
    "Competition Law",
    "Computational Mathematics",
    "Computer and Network Security",
    "Computer Network",
    "Computer Organization and Architecture",
    "Computer Programming",
    "Computer Simulation",
    "Computer Vision",
    "Conceptual Photography",
    "Concrete Structure 1",
    "Concrete Structure 2",
    "Conflict Studies",
    "Constitutional and Administrative Law",
    "Constitutional Procedural Law",
    "Construction Contracts and Legal",
    "Construction Cost Estimating",
    "Construction Execution and Demolition Methods",
    "Consumer Behavior",
    "Contemporary Issues in Global Marketing",
    "Content Creation",
    "Contract Drafting",
    "Contract Law",
    "Control System and Instrumentation",
    "Convergence News Media Presenting",
    "Convergence News Media Production & Reporting",
    "Corporate Finance",
    "Cost Accounting",
    "Cost Analysis",
    "Criminal Law",
    "Criminal Procedural Law",
    "Crisis Communication",
    "Culinary and Food and Beverage Service Management",
    "Cultural Studies and Semiotics",
    "Curriculum Design in Elementary School",
    "CV and Portfolio Design",
    "Cyber Security Fundamentals",
    "Cyber Security Project",
    "Data Analytic and Visualization Project",
    "Data Analytics",
    "Data Analytics for Agribusiness",
    "Data Science for Business Intelligence",
    "Data Science Programming",
    "Data Science Project",
    "Data Structure and Algorithm",
    "Data Visualization",
    "Database System",
    "Debt Restructuring and Bankruptcy Law",
    "Decision Analytics using Spreadsheets",
    "Deep Learning",
    "Defense Heritage",
    "Democratization in Asian Countries",
    "Derivatives/Fixed Income",
    "Design Critiques",
    "Design Drawing and Visualization",
    "Design Exhibition",
    "Design History",
    "Design of Machine Elements",
    "Design Research Methods",
    "Design Thinking and Psychology of Perception",
    "Destructive and Non-destructive Testing",
    "Diaspora Studies",
    "Differential Equation",
    "Digital Literacy",
    "Digital Forensics",
    "Digital HR Leadership",
    "Digital Learning in Elementary School 1",
    "Digital Learning in Elementary School 2",
    "Digital Literacy and Communication",
    "Digital Literacy, Communication and Media Studies",
    "Digital Marketing",
    "Digital Presentation Techniques 1",
    "Digital Presentation Techniques 2",
    "Digital Public Relations",
    "Digital Signal Processing",
    "Digital System and Laboratory",
    "Diplomacy",
    "Diplomacy and Intelligence",
    "Diplomacy and Technology",
    "Diplomacy in Asia, Pacific, and Africa",
    "Diplomatic Law",
    "Discover Palestine: History, People, and Statehood",
    "Discrete Mathematics",
    "Distributed and Parallel System",
    "Earthquake Engineering",
    "East Asia in the World",
    "Eco-Industrial Park Development",
    "Ecological Modelling",
    "Ecology 1",
    "Ecology 2",
    "Economic and Commercial Diplomacy",
    "Economic Survival 1: Business Creation / Internship Experience",
    "Economic Survival 2: Business Launch / Internship Experience",
    "Economics (Macro/Micro)",
    "Educational Management",
    "Electric Vehicle Technology",
    "Electrical Engineering Project Design-1 (Capstone Design-1)",
    "Electrical Engineering Project Design-2 (Capstone Design-2)",
    "Electrical Power Engineering",
    "Electronic Circuit Design and Analysis",
    "Elementary Linear Algebra",
    "E-Marketing and E-Commerce",
    "Embedded System",
    "Emotional Intelligence for Lawyers",
    "Employee Development and Talent Management",
    "Employee Relations",
    "Employment Law and Dispute Settlement",
    "Engineering Drawing",
    "Engineering Drawing (IE)",
    "Engineering Economics and Construction",
    "Engineering Economics and Economics",
    "Engineering Economics and Project Management",
    "Engineering Electromagnetics",
    "Engineering Materials and Equipment",
    "Engineering Mathematics",
    "Engineering Mechanics",
    "Engineering Mechanics 1",
    "Engineering Mechanics 2",
    "Engineering Mechanics 3",
    "English for Lawyers 1",
    "English for Lawyers 2",
    "Enterprise Resource Planning",
    "Environmental and Sustainability",
    "Environmental Chemistry",
    "Environmental Circular Economy",
    "Environmental Engineering Tools and Softwares",
    "Environmental Health, Safety, and Quality Management",
    "Environmental Impact Assesment",
    "Environmental Issues in IR",
    "Environmental Valuation and Feasibility",
    "Equity",
    "Ergonomic and Anthropometry",
    "Ergonomics",
    "Ethical Hacking",
    "Ethics in Architecture",
    "Event and Campaign Management",
    "Excel/R/Python (Software Training)",
    "Extended Reality",
    "Extension Studio: Commercial Office",
    "Extension Studio: Private-Commercial Residential Design",
    "Facility Design",
    "Family and Islamic Law",
    "Fashion for Professional",
    "Feasibility Study",
    "Feedback and Control Systems",
    "Film and TV Documentary",
    "Film Directing",
    "Film Editing and Sound",
    "Finance Management System",
    "Financial Management",
    "Financial Management for Film and New Media",
    "Financial Markets and Institutions",
    "Financial Statement Analysis",
    "Finite Element Analysis",
    "First-Year Writing Seminar",
    "Fluency and Speed Development",
    "Fluid Mechanics",
    "Fluid Mechanics and Hydraulics",
    "Food Enterpreneurship",
    "Food Packaging Innovation",
    "Food Processing Principles",
    "Food System",
    "Foreign Policy Analysis",
    "Forest and International Law",
    "Formal Language and Automata",
    "Foundation 1",
    "Foundation 2",
    "Foundation in Social Sciences and Humanities",
    "French 1",
    "French 2",
    "Fundamental of Data Science",
    "Fundamentals of Agricultural Science",
    "Fundamentals of Electrical Engineering",
    "Fuzzy Logic and Neural Network",
    "Game Asset and Design",
    "Game Assets",
    "Game Design",
    "Game Intelligence",
    "Game Programming",
    "Game Project",
    "Gastrodiplomacy and the Practice of Soft Power",
    "Gender Studies",
    "General Banking and Digital Finance",
    "Generalized Linear Models",
    "Generative AI for Data Science",
    "Global Business Environment",
    "Global Media, Conflict, and Peace",
    "Global Supply Chain Management",
    "Globalization and International Political Economy",
    "Globalization and Social Change",
    "Golf Class",
    "Golf Class Non-Credits",
    "Graphic Design Production Methods",
    "Guidance and Counselling",
    "Hazardous Waste Treatment and Remediation",
    "Health, Safety, and Environment",
    "Heat and Mass Transfer",
    "Highway Engineering",
    "History of Architecture",
    "History of Eastern Interior Design",
    "History of Western Interior Design",
    "Hotel and Resort Management",
    "Housing and Settlement",
    "Human Capital Management",
    "Human Comfort in Interior Design",
    "Human Rights and Human Security",
    "Hydrology and Drainage",
    "Illustration",
    "Image Processing and Recognition",
    "Inclusive Design",
    "Inclusive Education",
    "Indonesian and International Extradition Laws",
    "Indonesian Foreign & Security Policy",
    "Indonesian Language",
    "Indonesian Language 1 Non Credits",
    "Indonesian Ocean Policy",
    "Industrial Ecology",
    "Industrial Hygiene",
    "Industrial Organization Analysis and Design",
    "Industrial Psychology",
    "Information System Analysis and Design",
    "Insurance Law",
    "Integrated Practicum",
    "Integrated System",
    "Intellectual Property Law",
    "Intelligent Robotics",
    "Intercultural Communication",
    "Interior Decorations",
    "Interior Design",
    "Interior Design 2: Retail Space",
    "Interior Design 3: Commercial Office",
    "Interior Design 4: Public Space",
    "Interior Design Studio 1: Private-commercial Residential Design",
    "Interior Visualization",
    "Intermediate Accounting 1",
    "Intermediate Accounting 2",
    "Intermediate Animation",
    "Intermediate Computer Graphics",
    "Intermediate Drawing",
    "International and Domestic Tour and Travel Management",
    "International and Regional Organizations",
    "International Business",
    "International Climate Change Law",
    "International Corporate Sustainability",
    "International Culture and Communication",
    "International Curriculum Study",
    "International Dispute Settlement Law",
    "International Economic and Investment Law",
    "International Environmental Law",
    "International Financial Institutions",
    "International Human Rights Law",
    "International Humanitarian Law",
    "International Law",
    "International Law in Indonesian Law",
    "International Logistics",
    "International Migration",
    "International Moot Arbitration in Commercial Disputes",
    "International Organizations",
    "International Political Economy",
    "International Public Relations",
    "International Relations Seminar",
    "International Relations Theories",
    "International Security",
    "International Tax/Transfer Pricing",
    "International Trade",
    "Internationalization of Small and Medium Sized Enterprise",
    "Interpersonal Communication",
    "Introduction to Agricultural Mechanical Engineering",
    "Introduction to Agripreneurship",
    "Introduction to Architecture",
    "Introduction to Business",
    "Introduction to Cinematography",
    "Introduction to Civil Engineering",
    "Introduction to Communication",
    "Introduction to Criminology",
    "Introduction to Digital Business",
    "Introduction to Education",
    "Introduction to English as a Medium of Instruction (EMI)",
    "Introduction to Film and Media Studies",
    "Introduction to Global Business",
    "Introduction to Indonesian Law",
    "Introduction to Industrial Engineering",
    "Introduction to Information System",
    "Introduction to Interior Design Studies",
    "Introduction to International Relations",
    "Introduction to Law",
    "Introduction to Microprocessor and Microcontroller",
    "Introduction to Political Science",
    "Introduction to Programming",
    "Introduction to Public Relations",
    "Introduction to Real Analysis",
    "Introduction to U.S. Law",
    "Inventory and Asset Management",
    "Inventory and Asset Management Project",
    "Investment and Portfolio Management",
    "Investment Law",
    "Investment Management",
    "IoT Programming",
    "IoT Project",
    "IR Research Methods",
    "Irrigation and Water Building",
    "Japanese 1",
    "Japanese 2",
    "Kinematics and Dynamics of Mechanical System",
    "Land and Property for Corporate Lawyers",
    "Land Surveying",
    "Landscape Design",
    "Landscaping and Ornamental Plant",
    "Law Firm: Strategy and Management",
    "Law of Treaties",
    "Lawtech Startup: Funding and Management",
    "Layout Design",
    "Leadership",
    "Learning Assessment for Elementary School",
    "Legal Industry and Career Preparation",
    "Legal Project",
    "Legal Reasoning and Research Methodology",
    "Life Insurance 1",
    "Life Insurance 2",
    "Linear Algebra",
    "Linear Circuit Analysis",
    "Linear Regression and Time Series Model",
    "Logic and Critical Thinking",
    "Loss Model 1",
    "Loss Model 2",
    "Machine Learning",
    "Macroeconomic Principles in the Global Economy",
    "Macroeconomics",
    "Management and Organizational Behavior",
    "Management Control System",
    "Management Information System",
    "Managerial Accounting",
    "Managing Digital Convergence",
    "Mandarin 1",
    "Mandarin 2",
    "Manufacture Resource Planning Project",
    "Manufacturing Process",
    "Manufacturing Process 2",
    "Manufacturing Process and Metrology",
    "Manufacturing Resource Planning",
    "Marketing Communication",
    "Marketing Management",
    "Marketing Research",
    "Masterplan Design for Agrotourism",
    "Materials Engineering",
    "Materials Flow Analysis and Life Cycle Assessment",
    "Materials Science and Engineering",
    "Mathematical Statistics",
    "Mathematics",
    "Mathematics 1",
    "Mathematics 2",
    "Mathematics for the Elementary School 1",
    "Mathematics for the Elementary School 2",
    "Matrices and Vectors",
    "Mechanical Drawing and CAD",
    "Mechanical Vibration",
    "Mechanics of Materials",
    "Mechatronics and Robotics",
    "Media and Society",
    "Media Programming",
    "Media Theory",
    "Mediation and Peacekeeping Initiatives",
    "Mergers and Acquisitions Law",
    "MICE",
    "Microbiology",
    "Microcontroller",
    "Microeconomics",
    "Migration and Multiculturalism",
    "Mobile and Wireless Communications",
    "Mobile Programming",
    "Modern Physics",
    "Moot Court: Administrative Law",
    "Moot Court: Constitutional Law",
    "Moot Court: Criminal Law",
    "Moot Court: Employment Law",
    "Moot Court: Private Law",
    "Multicultural Education",
    "Multimedia Application Development",
    "Multimodal Communication",
    "Music Orchestra 1 Non-Credits",
    "Music Orchestra 2",
    "Music Orchestra 2 Non-Credits",
    "Music Orchestra 3",
    "Music Orchestra 3 Non-Credits",
    "Musical Arts in Education",
    "Musicpreneur: Production to Publishing Music",
    "Natural Language Processing",
    "Natural Language Understanding and Generation",
    "Natural Resource and Environmental Economic",
    "Negotiation Technique and Lobbying",
    "Network Security",
    "New and Emerging Media",
    "News Writing",
    "Numerical Method",
    "Numerical Methods with MATLAB",
    "Nusantara Visual Culture",
    "Object Oriented and Visual Programming",
    "Object-Oriented Programming",
    "Operating System Design",
    "Operational Audit",
    "Operational Research 1",
    "Operational Research 2",
    "Operations and Supply Chain Management",
    "Organization and Management",
    "Organizational Behavior",
    "Padel",
    "Pancasila",
    "Pavement Design",
    "Pension Fund",
    "Performance Management",
    "Perspective of Tourism",
    "Persuasive Communication Design",
    "Philosophy of Education",
    "Photography and Cinematography",
    "Photography and Digital Imaging",
    "Photography for Communication",
    "Physical Chemistry",
    "Physics 1",
    "Physics 1: Mechanics",
    "Physics 2",
    "Physics 2: Electromagnetics, Wave, and Optics",
    "Physics 3",
    "Podcasting",
    "Politics of ASEAN Member States",
    "Popular Culture and Globalization",
    "Postgraduate Degrees in Law and Other Subjects",
    "Practices of Retail Buying",
    "Precision Farming",
    "Pre-Internship",
    "Principles of Accounting 1",
    "Principles of Accounting 2",
    "Principles of Retail Buying",
    "Principles of Retailing",
    "Private Law",
    "Private Procedural Law",
    "Probability and Statistics",
    "Probability System Analysis for Electrical Engineering",
    "Probability Theory",
    "Product and Service Management",
    "Product Design and Development",
    "Production of Food Crop, Horticulture, and Plantation",
    "Production Planning, Inventory and Controlling",
    "Productions and Operations Management",
    "Professional English",
    "Professional Practices in Design",
    "Programming Concepts",
    "Programming for Business Analytics",
    "Project Management",
    "Projects: Tiktok Cinema: From Acting to Production",
    "Projects: Video Editing for TikTok Content I",
    "Projects: Video Editing for TikTok Content I Non Credits",
    "Promotion, Advertising, and Distribution for Film and New Media",
    "Property Development",
    "Psychology for Communication",
    "Psychology of Education",
    "Public Diplomacy",
    "Public Furniture Design",
    "Public Speaking",
    "Qualitative Communication Research Method",
    "Qualitative Interview",
    "Quality Control",
    "Quantitative Communication Research Method",
    "Regional Planning and Development",
    "Religion",
    "Remote Sensing and Spatial Planning",
    "Research Methodology",
    "Research Methodology for Engineering",
    "Research Methodology in Business",
    "Research Paper Writing",
    "Retail Operation Strategy",
    "Retail Seminar",
    "Risk Based Auditing",
    "Risk Management",
    "Robotics",
    "Robotics Design",
    "Rural Development and Sustainability",
    "Sales Management",
    "Science Concept 1",
    "Science Concept 2",
    "Scientific Methods for Environmental Management",
    "Security Compliance and Audit",
    "Security Risk Management",
    "Semiconductor Device Physics",
    "Server-Side Internet Programming",
    "Social Media and Big Data",
    "Social Media and Interactive Management",
    "Social Studies 1",
    "Social Studies 2",
    "Sociopreneur",
    "Software Engineering",
    "Soil Mechanics 1",
    "Soil Mechanics 2",
    "Solid Waste and Hazardous Waste Treatment",
    "Space Exploration Design",
    "Special Topics in Engineering I",
    "Special Topics in Engineering II",
    "Speed and Professionalism in Practice",
    "Statistics",
    "Statistics (Project)",
    "Statistics 1",
    "Statistics 2",
    "Statistics and Data Literacy",
    "Statistics and Probability",
    "Statistics and Probability 1",
    "Statistics and Probability 2",
    "Statistics for Communication",
    "Statistics, Problem Solving, and Decision Making",
    "Steel Structure 1",
    "Steel Structure 2",
    "Stochastic Process",
    "Strategic Issues in Human Capital Management",
    "Strategic Management",
    "Strategic Public Relations",
    "Study of War and Peace",
    "Supply and Sales Project",
    "Supply Chain Management",
    "Surface Packaging Design",
    "Survival English",
    "Survival Models",
    "Sustainable Agriculture Development",
    "Sustainable Development and Global Environmental Politics",
    "Sustainable Water Network System",
    "Syariah Banking and Finance",
    "System Modeling",
    "Talent Acquisition and Management",
    "Tax Auditing",
    "Tax Lab",
    "Tax Management/Tax Regulations",
    "Taxation 1",
    "Taxation 2",
    "Taylor Swift",
    "Teaching and Learning Media Development",
    "Teaching English for Young Learners (TEYL)",
    "Teaching Indonesian Language in Elementary School 1",
    "Teaching Indonesian Language in Elementary School 2",
    "Teaching Methodology in Elementary School",
    "Tennis",
    "The Dynamic of ASEAN",
    "The Dynamics of Middle East and North Africa (MENA) Region",
    "The Evolution of Strategic Thought",
    "The Rise and Fall of Multinational Corporations",
    "Theory of Communication",
    "Theory of Interest",
    "Thermodynamics 1",
    "Thermodynamics 2",
    "TikTok for Content Creators",
    "TikTok Marketing",
    "Tourism Attraction Management",
    "Tourism in International Relations",
    "Trade and Business Diplomacy",
    "Trade and Tax Law",
    "Traffic Engineering",
    "Transnational Communities and Cities",
    "Transport System 2",
    "Transportation System 1",
    "Typography",
    "UI/UX Design",
    "Unit Operations and Unit Processes",
    "Urban Architecture",
    "Urban Design",
    "US Foreign Policy",
    "Valuation of Information Technology Media Business",
    "Value Innovation of Information Technology",
    "Vernacular Design Studies",
    "Visual Brand Design",
    "Vocal Technique 1 Non-Credits",
    "Vocal Technique 2",
    "Vocal Technique 2 Non-Credits",
    "Wastewater Treatment Design",
    "Water Treatment Design",
    "Web Application Development",
    "Web Design",
    "Web Programming",
    "Wireless and Mobile Programming",
    "Work System Analysis and Design",
    "Workshop Drawing",
    "World Wars and World Orders",
    "Writing for Communication",
]


