# Generated by Django 5.2 on 2025-07-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='semester20251',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=50)),
                ('curriculum', models.CharField(max_length=50)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'semester_20251',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='semester20252',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=50)),
                ('curriculum', models.CharField(max_length=50)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'semester_20252',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='assignlecturer20251',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer_day', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicapp.semester20251')),
            ],
            options={
                'db_table': 'assignlecturer20251',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='assignlecturer20252',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer_day', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicapp.semester20252')),
            ],
            options={
                'db_table': 'assignlecturer20252',
                'managed': True,
            },
        ),
    ]
