# Generated by Django 5.2 on 2025-07-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer_name', models.CharField(max_length=100)),
                ('lecturer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('current_working_day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecturerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=100)),
                ('time_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('day_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('room_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecturer_preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='semester20243',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=50)),
                ('curriculum', models.CharField(max_length=50)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'semester_20243',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='semester20251',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=50)),
                ('curriculum', models.CharField(max_length=50)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'semester_20251',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='semester20252',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=50)),
                ('curriculum', models.CharField(max_length=50)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'semester_20252',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='semester20253',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=50)),
                ('curriculum', models.CharField(max_length=50)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'semester_20253',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viewschedule20251',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer1', models.CharField(max_length=255)),
                ('lecturer2', models.CharField(blank=True, max_length=255, null=True)),
                ('lecturer3', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('schedule_time', models.CharField()),
                ('room', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'schedule20251',
            },
        ),
        migrations.CreateModel(
            name='Viewschedule20252',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer1', models.CharField(max_length=255)),
                ('lecturer2', models.CharField(blank=True, max_length=255, null=True)),
                ('lecturer3', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('schedule_time', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'schedule20252',
            },
        ),
        migrations.CreateModel(
            name='Viewschedule20253',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer1', models.CharField(max_length=255)),
                ('lecturer2', models.CharField(blank=True, max_length=255, null=True)),
                ('lecturer3', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('schedule_time', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'schedule20253',
            },
        ),
        migrations.CreateModel(
            name='assignlecturer20251',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer_day', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicapp.semester20251')),
            ],
            options={
                'db_table': 'assignlecturer20251',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='assignlecturer20252',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer_day', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicapp.semester20252')),
            ],
            options={
                'db_table': 'assignlecturer20252',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='assignlecturer20253',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer_day', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicapp.semester20253')),
            ],
            options={
                'db_table': 'assignlecturer20253',
                'managed': True,
            },
        ),
    ]
