# Generated by Django 5.2 on 2025-07-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formsemester20251',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=50)),
                ('curriculum', models.CharField(max_length=50)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'form20251',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='formsemester20252',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('curriculum', models.CharField(max_length=100)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'form20252',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='formsemester20253',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('curriculum', models.CharField(max_length=100)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'form20253',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='formsemester20261',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_session', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('curriculum', models.CharField(max_length=100)),
                ('major_class', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lecturer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'form20261',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecturer_name', models.CharField(max_length=100)),
                ('lecturer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('current_working_day', models.IntegerField(blank=True, null=True)),
                ('time_preferences', models.TextField(blank=True, null=True)),
                ('day_preferences', models.TextField(blank=True, null=True)),
                ('room_preferences', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecturerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=100)),
                ('time_preference', models.CharField(max_length=50)),
                ('day_preference', models.CharField(max_length=50)),
                ('room_preference', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecturer_preference',
                'managed': False,
            },
        ),
    ]
