# Generated by Django 5.2 on 2025-07-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicapp', '0002_formsemester20251_formsemester20252_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lecturerpreference',
            table='lecturer_preferences',
        ),
    ]
